name: nayron_keeper_api
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  conduit: ^4.3.7
  conduit_core: ^4.3.6
  uuid: ^4.3.1
  vector_math: ^2.1.4

dev_dependencies:
  test: ^1.21.6
  conduit_test: ^4.3.6
